#!/bin/bash
# Setup bird CLI with X/Twitter cookies from BrowserOS
# Auto-detects BrowserOS CDP port and extracts cookies

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIRD_CONFIG="$HOME/.config/bird"
BIRD_CONFIG_FILE="$BIRD_CONFIG/config.json5"

echo "🔧 Setting up bird CLI with BrowserOS cookies..."

# Ensure bird config directory exists
mkdir -p "$BIRD_CONFIG"

# Find BrowserOS CDP port (skip MCP ports 9100 and 10864)
echo "🔍 Finding BrowserOS CDP port..."
BROWSEROS_PORT=$(ss -tlnp 2>/dev/null | grep browseros | grep -v '9100\|10864' | head -1 | awk '{print $4}' | cut -d: -f2)

if [ -z "$BROWSEROS_PORT" ]; then
  echo "❌ BrowserOS CDP port not found"
  echo "📦 Starting BrowserOS..."
  bash "$SCRIPT_DIR/ensure-browseros.sh"
  sleep 3
  BROWSEROS_PORT=$(ss -tlnp 2>/dev/null | grep browseros | grep -v '9100\|10864' | head -1 | awk '{print $4}' | cut -d: -f2)
fi

if [ -z "$BROWSEROS_PORT" ]; then
  echo "❌ Could not find or start BrowserOS"
  exit 1
fi

echo "✅ Found BrowserOS on port $BROWSEROS_PORT"

# Extract cookies using Node.js script
export BROWSEROS_PORT
echo "🍪 Extracting X cookies..."

# Use a simpler inline Node script to avoid hanging
AUTH_TOKEN=$(node -e "
const { chromium } = require('playwright');
(async () => {
  try {
    const browser = await chromium.connectOverCDP('http://127.0.0.1:$BROWSEROS_PORT');
    const context = browser.contexts()[0];
    const cookies = await context.cookies('https://x.com');
    const authToken = cookies.find(c => c.name === 'auth_token');
    if (authToken) {
      console.log(authToken.value);
      await browser.close();
    } else {
      process.exit(1);
    }
  } catch (e) {
    console.error('Error:', e.message);
    process.exit(1);
  }
})();
" 2>/dev/null)

CT0=$(node -e "
const { chromium } = require('playwright');
(async () => {
  try {
    const browser = await chromium.connectOverCDP('http://127.0.0.1:$BROWSEROS_PORT');
    const context = browser.contexts()[0];
    const cookies = await context.cookies('https://x.com');
    const ct0 = cookies.find(c => c.name === 'ct0');
    if (ct0) {
      console.log(ct0.value);
      await browser.close();
    } else {
      process.exit(1);
    }
  } catch (e) {
    console.error('Error:', e.message);
    process.exit(1);
  }
})();
" 2>/dev/null)

if [ -z "$AUTH_TOKEN" ] || [ -z "$CT0" ]; then
  echo "❌ Failed to extract cookies. Make sure you're logged into x.com in BrowserOS."
  echo "💡 Try visiting https://x.com in BrowserOS first"
  exit 1
fi

echo "✅ Cookies extracted successfully"

# Create/update bird config
cat > "$BIRD_CONFIG_FILE" << EOF
{
  // Auto-generated by x-research skill
  // Generated: $(date)
  cookieSource: ["custom"],
  auth_token: "$AUTH_TOKEN",
  ct0: "$CT0",
  timeoutMs: 20000
}
EOF

echo "✅ bird CLI configured at $BIRD_CONFIG_FILE"
echo ""
echo "🧪 Testing configuration..."
if bird whoami &>/dev/null; then
  echo "✅ bird CLI is ready!"
  echo ""
  echo "📝 Usage:"
  echo "  bird tweet 'your message'"
  echo "  bird thread <url>"
  echo "  bird user-tweets @handle -n 10"
else
  echo "⚠️  bird test failed, but configuration is saved"
  echo "   You may need to log into x.com in BrowserOS"
fi
